{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Facial Emotion Feature Extraction\n",
    "### Raymond Postrero\n",
    "### CS41S2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: opencv-python in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (4.10.0.84)\n",
      "Requirement already satisfied: numpy>=1.17.0 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from opencv-python) (1.21.5)\n",
      "Collecting dlib\n",
      "  Using cached dlib-19.24.6.tar.gz (3.4 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib\n",
      "  Running setup.py install for dlib: started\n",
      "  Running setup.py install for dlib: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × python setup.py bdist_wheel did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [41 lines of output]\n",
      "      running bdist_wheel\n",
      "      running build\n",
      "      running build_ext\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      \n",
      "                         CMake is not installed on your system!\n",
      "      \n",
      "          Or it is possible some broken copy of cmake is installed on your system.\n",
      "          It is unfortunately very common for python package managers to include\n",
      "          broken copies of cmake.  So if the error above this refers to some file\n",
      "          path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "          should delete that broken copy of cmake from your computer.\n",
      "      \n",
      "          Instead, please get an official copy of cmake from one of these known good\n",
      "          sources of an official cmake:\n",
      "              - cmake.org (this is how windows users should get cmake)\n",
      "              - apt install cmake (for Ubuntu or Debian based systems)\n",
      "              - yum install cmake (for Redhat or CenOS based systems)\n",
      "      \n",
      "          On a linux machine you can run `which cmake` to see what cmake you are\n",
      "          actually using.  If it tells you it's some cmake from any kind of python\n",
      "          packager delete it and install an official cmake.\n",
      "      \n",
      "          More generally, cmake is not installed if when you open a terminal window\n",
      "          and type\n",
      "             cmake --version\n",
      "          you get an error.  So you can use that as a very basic test to see if you\n",
      "          have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "          same terminal window from which you are reading this error message, then\n",
      "          you have not installed cmake.  Windows users should take note that they\n",
      "          need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "          can't run commands that are not in your PATH.  This is how the PATH works\n",
      "          on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "          common problem on windows and rarely a problem on Linux.\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × Running setup.py install for dlib did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [43 lines of output]\n",
      "      running install\n",
      "      C:\\Users\\Raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages\\setuptools\\command\\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "        setuptools.SetuptoolsDeprecationWarning,\n",
      "      running build\n",
      "      running build_ext\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      \n",
      "                         CMake is not installed on your system!\n",
      "      \n",
      "          Or it is possible some broken copy of cmake is installed on your system.\n",
      "          It is unfortunately very common for python package managers to include\n",
      "          broken copies of cmake.  So if the error above this refers to some file\n",
      "          path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "          should delete that broken copy of cmake from your computer.\n",
      "      \n",
      "          Instead, please get an official copy of cmake from one of these known good\n",
      "          sources of an official cmake:\n",
      "              - cmake.org (this is how windows users should get cmake)\n",
      "              - apt install cmake (for Ubuntu or Debian based systems)\n",
      "              - yum install cmake (for Redhat or CenOS based systems)\n",
      "      \n",
      "          On a linux machine you can run `which cmake` to see what cmake you are\n",
      "          actually using.  If it tells you it's some cmake from any kind of python\n",
      "          packager delete it and install an official cmake.\n",
      "      \n",
      "          More generally, cmake is not installed if when you open a terminal window\n",
      "          and type\n",
      "             cmake --version\n",
      "          you get an error.  So you can use that as a very basic test to see if you\n",
      "          have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "          same terminal window from which you are reading this error message, then\n",
      "          you have not installed cmake.  Windows users should take note that they\n",
      "          need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "          can't run commands that are not in your PATH.  This is how the PATH works\n",
      "          on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "          common problem on windows and rarely a problem on Linux.\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: legacy-install-failure\n",
      "\n",
      "× Encountered error while trying to install package.\n",
      "╰─> dlib\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (1.3.5)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: numpy>=1.17.3 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from pandas) (1.21.5)\n",
      "Requirement already satisfied: pytz>=2017.3 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from pandas) (2022.7)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (3.5.3)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (1.21.5)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (9.4.0)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (22.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (2.8.2)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (3.0.9)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (4.25.0)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: typing-extensions in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from kiwisolver>=1.0.1->matplotlib) (4.4.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install opencv-python \n",
    "!pip install dlib\n",
    "!pip install pandas\n",
    "!pip install matplotlib "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting dlib\n",
      "  Using cached dlib-19.24.6.tar.gz (3.4 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib\n",
      "  Running setup.py install for dlib: started\n",
      "  Running setup.py install for dlib: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × python setup.py bdist_wheel did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [41 lines of output]\n",
      "      running bdist_wheel\n",
      "      running build\n",
      "      running build_ext\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      \n",
      "                         CMake is not installed on your system!\n",
      "      \n",
      "          Or it is possible some broken copy of cmake is installed on your system.\n",
      "          It is unfortunately very common for python package managers to include\n",
      "          broken copies of cmake.  So if the error above this refers to some file\n",
      "          path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "          should delete that broken copy of cmake from your computer.\n",
      "      \n",
      "          Instead, please get an official copy of cmake from one of these known good\n",
      "          sources of an official cmake:\n",
      "              - cmake.org (this is how windows users should get cmake)\n",
      "              - apt install cmake (for Ubuntu or Debian based systems)\n",
      "              - yum install cmake (for Redhat or CenOS based systems)\n",
      "      \n",
      "          On a linux machine you can run `which cmake` to see what cmake you are\n",
      "          actually using.  If it tells you it's some cmake from any kind of python\n",
      "          packager delete it and install an official cmake.\n",
      "      \n",
      "          More generally, cmake is not installed if when you open a terminal window\n",
      "          and type\n",
      "             cmake --version\n",
      "          you get an error.  So you can use that as a very basic test to see if you\n",
      "          have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "          same terminal window from which you are reading this error message, then\n",
      "          you have not installed cmake.  Windows users should take note that they\n",
      "          need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "          can't run commands that are not in your PATH.  This is how the PATH works\n",
      "          on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "          common problem on windows and rarely a problem on Linux.\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × Running setup.py install for dlib did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [43 lines of output]\n",
      "      running install\n",
      "      C:\\Users\\Raymond\\anaconda3\\envs\\venv3.7\\lib\\site-packages\\setuptools\\command\\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "        setuptools.SetuptoolsDeprecationWarning,\n",
      "      running build\n",
      "      running build_ext\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      \n",
      "                         CMake is not installed on your system!\n",
      "      \n",
      "          Or it is possible some broken copy of cmake is installed on your system.\n",
      "          It is unfortunately very common for python package managers to include\n",
      "          broken copies of cmake.  So if the error above this refers to some file\n",
      "          path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "          should delete that broken copy of cmake from your computer.\n",
      "      \n",
      "          Instead, please get an official copy of cmake from one of these known good\n",
      "          sources of an official cmake:\n",
      "              - cmake.org (this is how windows users should get cmake)\n",
      "              - apt install cmake (for Ubuntu or Debian based systems)\n",
      "              - yum install cmake (for Redhat or CenOS based systems)\n",
      "      \n",
      "          On a linux machine you can run `which cmake` to see what cmake you are\n",
      "          actually using.  If it tells you it's some cmake from any kind of python\n",
      "          packager delete it and install an official cmake.\n",
      "      \n",
      "          More generally, cmake is not installed if when you open a terminal window\n",
      "          and type\n",
      "             cmake --version\n",
      "          you get an error.  So you can use that as a very basic test to see if you\n",
      "          have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "          same terminal window from which you are reading this error message, then\n",
      "          you have not installed cmake.  Windows users should take note that they\n",
      "          need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "          can't run commands that are not in your PATH.  This is how the PATH works\n",
      "          on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "          common problem on windows and rarely a problem on Linux.\n",
      "      \n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      ================================================================================\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: legacy-install-failure\n",
      "\n",
      "× Encountered error while trying to install package.\n",
      "╰─> dlib\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n"
     ]
    }
   ],
   "source": [
    "!pip install dlib\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'dlib'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_26568\\3907108405.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mdlib\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'dlib'"
     ]
    }
   ],
   "source": [
    "import os \n",
    "import cv2 \n",
    "import dlib \n",
    "import pandas as pd \n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Path to the JAFFE dataset\n",
    "dataset_path = 'jaffedbase'\n",
    "\n",
    "# Load the images\n",
    "images = []\n",
    "image_filenames = []\n",
    "for filenames in os.listdir(dataset_path):\n",
    "    if filenames.endswith('.tiff'):\n",
    "        image = cv2.imread(os.path.join(dataset_path, filenames))\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "        images.append(image)\n",
    "        image_filenames.append(filenames)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting imutils\n",
      "  Downloading imutils-0.5.4.tar.gz (17 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Building wheels for collected packages: imutils\n",
      "  Building wheel for imutils (setup.py): started\n",
      "  Building wheel for imutils (setup.py): finished with status 'done'\n",
      "  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25854 sha256=63abb5985919a888983381dc46a96970d3b075081384de1f7a3100aaf721bfe9\n",
      "  Stored in directory: c:\\users\\raymond\\appdata\\local\\pip\\cache\\wheels\\35\\e4\\69\\cb99d996d14a2971b79b990d68b05a17d58ce530ff96090dfc\n",
      "Successfully built imutils\n",
      "Installing collected packages: imutils\n",
      "Successfully installed imutils-0.5.4\n"
     ]
    }
   ],
   "source": [
    "!pip install imutils"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'dlib'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_26568\\3667433214.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# import the necessary packages\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mimutils\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mface_utils\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mdlib\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'dlib'"
     ]
    }
   ],
   "source": [
    "# import the necessary packages\n",
    "from imutils import face_utils\n",
    "import dlib\n",
    "import cv2\n",
    " \n",
    "# initialize dlib's face detector (HOG-based) and then create\n",
    "# the facial landmark predictor\n",
    "p = \"shape_predictor_68_face_landmarks.dat\"\n",
    "detector = dlib.get_frontal_face_detector()\n",
    "predictor = dlib.shape_predictor(p)\n",
    "\n",
    "cap = cv2.VideoCapture(0)\n",
    " \n",
    "while True:\n",
    "    # load the input image and convert it to grayscale\n",
    "    _, image = cap.read()\n",
    "    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\n",
    "        \n",
    "    # detect faces in the grayscale image\n",
    "    rects = detector(gray, 0)\n",
    "    \n",
    "    # loop over the face detections\n",
    "    for (i, rect) in enumerate(rects):\n",
    "        # determine the facial landmarks for the face region, then\n",
    "        # convert the facial landmark (x, y)-coordinates to a NumPy\n",
    "        # array\n",
    "        shape = predictor(gray, rect)\n",
    "        shape = face_utils.shape_to_np(shape)\n",
    "    \n",
    "        # loop over the (x, y)-coordinates for the facial landmarks\n",
    "        # and draw them on the image\n",
    "        for (x, y) in shape:\n",
    "            cv2.circle(image, (x, y), 2, (0, 255, 0), -1)\n",
    "    \n",
    "    # show the output image with the face detections + facial landmarks\n",
    "    cv2.imshow(\"Output\", image)\n",
    "    k = cv2.waitKey(5) & 0xFF\n",
    "    if k == 27:\n",
    "        break\n",
    "\n",
    "cv2.destroyAllWindows()\n",
    "cap.release()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv3.7",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
